### ISSUE TITLE
breaking changes (GTK 3.22)

### ISSUE THREAD

**Issue by hauntingEcho** [Elbullazul/B00merang-Project#15]
running any GTK3 program results in unusable sliders, as GTK broke themes again in 3.20.  I've attached the contents of stderr from running `pavucontrol` with all three themes

`dpkg -s libgtk-3-0 | grep Version`
Version: 3.22.8-1

Running on Debian Stretch with XFCE

[green.txt](https://github.com/B00merang-Project/B00merang-Themes/files/826672/green.txt)
[dark.txt](https://github.com/B00merang-Project/B00merang-Themes/files/826671/dark.txt)
[glass.txt](https://github.com/B00merang-Project/B00merang-Themes/files/826673/glass.txt)

**Comment by Elbullazul** [comment]
@hauntingEcho yes, even though we have ported the big part of our themes to 3.20, the B00merang Themes are still lagging behind.

since we're taking a break on the development of Windows/Apple/Google themes, maybe we can port them, at least to make them work with 'basic features' on 3.20

I'll keep you updated on our progress

**Comment by Elbullazul** [comment]
All supported B00merang themes are now compatible with GTK 3.20
